<?php

use App\Http\Controllers\Admin\AboutSettingController;
use App\Http\Controllers\Admin\AuctionController as AdminAuctionController;
use App\Http\Controllers\Admin\CatalogController;
use App\Http\Controllers\Admin\ContactController as AdminContactController;
use App\Http\Controllers\Admin\ContactSettingController;
use App\Http\Controllers\Admin\ControlController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\EnvironmentController as AdminEnvironmentController;
use App\Http\Controllers\Admin\GalleryController as AdminGalleryController;
use App\Http\Controllers\Admin\HistoryController;
use App\Http\Controllers\Admin\ItemController as AdminItemController;
use App\Http\Controllers\Admin\NewsController as AdminNewsController;
use App\Http\Controllers\Admin\OtherController;
use App\Http\Controllers\Admin\ProductController as AdminProductController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\SkillController;
use App\Http\Controllers\Admin\SliderController;
use App\Http\Controllers\Admin\SloganController;
use App\Http\Controllers\Admin\TeamController;
use App\Http\Controllers\Admin\TicketController as AdminTicketController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Auth\LogoutController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\Panel\PanelController;
use App\Http\Controllers\Panel\UserController as PanelUserController;
use App\Http\Controllers\Site\AboutController;
use App\Http\Controllers\Site\AuctionController;
use App\Http\Controllers\Site\Auth\LoginController;
use App\Http\Controllers\Site\Auth\RegisterController;
use App\Http\Controllers\Site\ContactController;
use App\Http\Controllers\Site\ContactUsController;
use App\Http\Controllers\Site\EnvironmentController;
use App\Http\Controllers\Site\GalleryController;
use App\Http\Controllers\Site\HomeController;
use App\Http\Controllers\Site\ItemController;
use App\Http\Controllers\Site\NewsController;
use App\Http\Controllers\Site\ProductController;
use App\Http\Controllers\Site\TicketController;
use App\Http\Middleware\AdminMiddleware;
use App\Http\Middleware\CustomAuth;
use App\Models\Other;
use GuzzleHttp\Psr7\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/',[HomeController::class,'index'])->name('home');
Route::post('/register',[RegisterController::class,'register']);
Route::post('/login',[LoginController::class,'login']);
Route::get('/logout',[LogoutController::class,'logout']);
Route::get('/contact-us',[ContactUsController::class,'index']);
Route::post('/contact-us',[ContactController::class,'store']);
Route::get('/gallery',[GalleryController::class,'index']);
Route::get('/news',[NewsController::class,'index']);
Route::get('/news/search',[NewsController::class,'search']);
Route::get('/news/{id}',[NewsController::class,'show']);
Route::get('/about-us',[AboutController::class,'index']);
Route::get('/environment',[EnvironmentController::class,'index']);
Route::get('/auction',[AuctionController::class,'index']);
Route::get('/products',[ProductController::class,'index']);
Route::get('/products/{id}',[ProductController::class,'show']);
Route::get('/items/{id}',[ItemController::class,'show']);
Route::get('reset-password-token',[ResetPasswordController::class,'index']);
Route::post('reset-password-token',[ResetPasswordController::class,'sendToken']);
Route::get('new-password',[ResetPasswordController::class,'newPassword']);
Route::post('new-password',[ResetPasswordController::class,'changePassword']);
Route::prefix('panel')->middleware([CustomAuth::class])->group(function(){
   Route::get('/',[PanelController::class,'index']);
   Route::get('tickets',[TicketController::class,'index']);
   Route::get('tickets/create',[TicketController::class,'create']);
   Route::post('tickets',[TicketController::class,'store']);
   Route::get('tickets/{id}',[TicketController::class,'show']);
   Route::post('tickets/message/{id}', [TicketController::class, 'storeMessage']);
    Route::get('control', [ControlController::class, 'edit']);
    Route::post('control', [ControlController::class, 'update']);
    Route::get('profile', [PanelUserController::class, 'edit']);
    Route::post('profile', [PanelUserController::class, 'update']);
});
Route::prefix('admin')->middleware([CustomAuth::class, AdminMiddleware::class])->group(function () {
    Route::get('dashboard',[DashboardController::class,'index']);
    Route::get('users',[UserController::class,'index']);
    Route::get('users/{id}/edit',[UserController::class,'edit']);
    Route::post('users/{id}/update',[UserController::class,'update']);
    Route::get('roles', [RoleController::class, 'index']);
    Route::post('roles', [RoleController::class, 'store']);
    Route::get('roles/{id}', [RoleController::class, 'show']);
    Route::get('roles/{id}/edit', [RoleController::class, 'edit']);
    Route::post('roles/{id}/update', [RoleController::class, 'update']);
    Route::post('roles/{id}/delete', [RoleController::class, 'delete']);
    Route::post('roles/{id}/updatePermission', [RoleController::class, 'updatePermission']);
    Route::get('news',[AdminNewsController::class,'index']);
    Route::get('news/create',[AdminNewsController::class,'create']);
    Route::post('news',[AdminNewsController::class,'store']);
    Route::get('news/{id}/edit',[AdminNewsController::class,'edit']);
    Route::post('news/{id}/update',[AdminNewsController::class,'update']);
    Route::post('news/{id}/delete',[AdminNewsController::class,'delete']);
    Route::get('sliders',[SliderController::class,'index']);
    Route::get('sliders/create',[SliderController::class,'create']);
    Route::post('sliders',[SliderController::class,'store']);
    Route::get('sliders/{id}/edit',[SliderController::class,'edit']);
    Route::post('sliders/{id}/update',[SliderController::class,'update']);
    Route::post('sliders/{id}/delete',[SliderController::class,'delete']);
    Route::get('galleries', [AdminGalleryController::class, 'index']);
    Route::get('galleries/create', [AdminGalleryController::class, 'create']);
    Route::post('galleries', [AdminGalleryController::class, 'store']);
    Route::get('galleries/{id}/edit', [AdminGalleryController::class, 'edit']);
    Route::post('galleries/{id}/update', [AdminGalleryController::class, 'update']);
    Route::post('galleries/{id}/delete', [AdminGalleryController::class, 'delete']);
    Route::get('contact-us',[ContactSettingController::class,'index']);
    Route::post('contact-us',[ContactSettingController::class,'update']);
    Route::get('slogans', [SloganController::class, 'index']);
    Route::get('slogans/create', [SloganController::class, 'create']);
    Route::post('slogans', [SloganController::class, 'store']);
    Route::get('slogans/{id}/edit', [SloganController::class, 'edit']);
    Route::post('slogans/{id}/update', [SloganController::class, 'update']);
    Route::post('slogans/{id}/delete', [SloganController::class, 'delete']);
    Route::get('team', [TeamController::class, 'index']);
    Route::get('team/create', [TeamController::class, 'create']);
    Route::post('team', [TeamController::class, 'store']);
    Route::get('team/{id}/edit', [TeamController::class, 'edit']);
    Route::post('team/{id}/update', [TeamController::class, 'update']);
    Route::post('team/{id}/delete', [TeamController::class, 'delete']);
    Route::get('skills', [SkillController::class, 'index']);
    Route::get('skills/create', [SkillController::class, 'create']);
    Route::post('skills', [SkillController::class, 'store']);
    Route::get('skills/{id}/edit', [SkillController::class, 'edit']);
    Route::post('skills/{id}/update', [SkillController::class, 'update']);
    Route::post('skills/{id}/delete', [SkillController::class, 'delete']);
    Route::get('histories', [HistoryController::class, 'index']);
    Route::get('histories/create', [HistoryController::class, 'create']);
    Route::post('histories', [HistoryController::class, 'store']);
    Route::get('histories/{id}/edit', [HistoryController::class, 'edit']);
    Route::post('histories/{id}/update', [HistoryController::class, 'update']);
    Route::post('histories/{id}/delete', [HistoryController::class, 'delete']);
    Route::get('products', [AdminProductController::class, 'index']);
    Route::get('products/create', [AdminProductController::class, 'create']);
    Route::post('products', [AdminProductController::class, 'store']);
    Route::get('products/{id}/edit', [AdminProductController::class, 'edit']);
    Route::post('products/{id}/update', [AdminProductController::class, 'update']);
    Route::post('products/{id}/delete', [AdminProductController::class, 'delete']);
    Route::get('products/{id}/items', [AdminItemController::class, 'index']);
    Route::get('products/{id}/items/create', [AdminItemController::class, 'create']);
    Route::post('products/{id}/items', [AdminItemController::class, 'store']);
    Route::get('items/{id}/edit', [AdminItemController::class, 'edit']);
    Route::post('items/{id}/update', [AdminItemController::class, 'update']);
    Route::post('items/{id}/delete', [AdminItemController::class, 'delete']);
    Route::get('items/{id}/catalogs', [CatalogController::class, 'index']);
    Route::get('items/{id}/catalogs/create', [CatalogController::class, 'create']);
    Route::post('items/{id}/catalogs', [CatalogController::class, 'store']);
    Route::get('catalogs/{id}/edit', [CatalogController::class, 'edit']);
    Route::post('catalogs/{id}/update', [CatalogController::class, 'update']);
    Route::post('catalogs/{id}/delete', [CatalogController::class, 'delete']);
    Route::get('about',[AboutSettingController::class,'edit']);
    Route::post('about',[AboutSettingController::class,'update']);
    Route::get('contacts',[AdminContactController::class,'index']);
    Route::get('contacts/{id}',[AdminContactController::class,'show']);
    Route::get('other', [OtherController::class, 'edit']);
    Route::post('other', [OtherController::class, 'update']);
    Route::get('tickets', [AdminTicketController::class, 'index']);
    Route::post('tickets/close/{id}', [AdminTicketController::class, 'close']);
    Route::post('tickets/message/{id}/delete', [AdminTicketController::class, 'deleteMessage']);
    Route::get('tickets/{id}', [AdminTicketController::class, 'show']);
    Route::post('tickets/message/{id}', [AdminTicketController::class, 'storeMessage']);
    Route::get('auction', [AdminAuctionController::class, 'edit']);
    Route::post('auction', [AdminAuctionController::class, 'update']);
    Route::get('environment', [AdminEnvironmentController::class, 'edit']);
    Route::post('environment', [AdminEnvironmentController::class, 'update']);
});
